#!/bin/bash

cd ./rebabel_scripts

echo 'Creating Python virtual environment (this may take a while)...'
python3 -m venv .venv

echo 'Activating Python virtual environment...'
source .venv/bin/activate

echo 'Installing dependencies in requirements.txt...'
pip install -r requirements.txt

echo 'Deactivating Python virtual environment...'
deactivate
