name: Publish Gap App 
on:
  push:
    branches:
      - main
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: main
    - uses: actions/setup-node@master
      with:
        node-version: '18'
    - run: ls
